CREATE TABLE KaliLogs(
	KaliLogID INTEGER PRIMARY KEY NOT NULL,
	LogLevel INTEGER NOT NULL,
	Category TEXT,
	EventID INTEGER,
	EventName TEXT,
	RenderedMessage TEXT NOT NULL,
	Scopes TEXT,
	ExceptionJSON TEXT,
	DateTimeCreated TIMESTAMP NOT NULL,
	DateTimeModified TIMESTAMP NOT NULL,
	RowVer INT NOT NULL
)